### ISSUE TITLE
Undefined variable notice

### ISSUE THREAD

**Issue by Toutouwai** [BitPoet/FormBuilderMultiplier#3]
Another little issue [here](https://github.com/BitPoet/FormBuilderMultiplier/blob/e835139fefcb925364e1de63a6de6c675adc8bf8/FormBuilderMultiplier.module#L64)

**Comment by BitPoet** [comment]
Thanks for reporting, I've removed the superfluous concatenate operator in dev and will push to master as soon as it's tested.
